#!/bin/sh

KERNEL_VERSION="$1"
KEYDIR="/usr/share/secureboot-signing"
SIGN_FILE="/usr/src/linux-headers-${KERNEL_VERSION}/scripts/sign-file"

GREEN="\033[1;32m"
RESET="\033[0m"

# Signer les modules dans misc
if [ -d "/usr/lib/modules/${KERNEL_VERSION}/misc" ]; then
	find "/usr/lib/modules/${KERNEL_VERSION}/misc/" -name '*.ko' | while read -r module; do
		"$SIGN_FILE" sha256 "$KEYDIR/MOK.priv" "$KEYDIR/MOK.der" "$module" || break
	done
	echo -e "${GREEN}[+] Modules Updates signés avec succès${RESET}"
fi

# Signer les modules dans updates
if [ -d "/usr/lib/modules/${KERNEL_VERSION}/updates" ]; then
	find "/usr/lib/modules/${KERNEL_VERSION}/updates/" -name '*.ko' | while read -r module; do
		"$SIGN_FILE" sha256 "$KEYDIR/MOK.priv" "$KEYDIR/MOK.der" "$module" || break
	done
	echo -e "${GREEN}[+] Modules DKMS signés avec succès${RESET}"
fi
